/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in normal development. It is included here
// so the handoff project type-checks before the first local dev run.
